[package]
name = "luad-dialect-lua55"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
luad-core = { workspace = true }
serde = { workspace = true }
schemars = { workspace = true }
thiserror = { workspace = true }
hex = { workspace = true }
sha2 = { workspace = true }
